# Generated by Django 4.1.1 on 2022-09-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_acompanante_delete_arriendo_delete_checkin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id_acompanante', models.DecimalField(decimal_places=11, max_digits=11)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut_acomp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.DecimalField(decimal_places=11, max_digits=11)),
                ('edad', models.DecimalField(decimal_places=11, max_digits=11)),
                ('sexo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'acompanante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('tarifa', models.CharField(max_length=50)),
                ('condicion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'arriendo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id_check_in', models.DecimalField(db_column='id_check-in', decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'checkin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id_check_out', models.DecimalField(db_column='id_check-out', decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('fecha_regreso', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'checkout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut_cliente', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=20)),
                ('pass_field', models.CharField(db_column='pass', max_length=20)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.DecimalField(decimal_places=11, max_digits=11)),
            ],
            options={
                'db_table': 'conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_depto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('num_depto', models.IntegerField()),
                ('muebles', models.CharField(max_length=200)),
                ('internet', models.CharField(max_length=50)),
                ('cable', models.CharField(max_length=50)),
                ('calefaccion', models.CharField(max_length=50)),
                ('precio', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleMantencion',
            fields=[
                ('id_detalle', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'detalle_mantencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleViaje',
            fields=[
                ('id_detalle', models.DecimalField(decimal_places=11, max_digits=11)),
                ('descripcion', models.CharField(max_length=50)),
                ('detalle_viaje_id', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_viaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id_estadia', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('fecha_ini', models.DateField()),
                ('fecha_term', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('valor_pendiente', models.DecimalField(decimal_places=11, max_digits=11)),
            ],
            options={
                'db_table': 'estadia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.FloatField()),
                ('rut_fun', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_fun', models.CharField(max_length=50)),
                ('apellido_fun', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_inventario', models.DateField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('tipo_mant', models.CharField(max_length=50)),
                ('fecha_mant', models.DateField()),
                ('valor', models.DecimalField(decimal_places=11, max_digits=11)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mantencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('num_reserva', models.DecimalField(decimal_places=20, max_digits=20)),
                ('fecha_reserva', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=20, max_digits=20)),
                ('cant_acompanante', models.DecimalField(blank=True, decimal_places=11, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id_servicio', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'servicio_extra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('credito', models.DecimalField(decimal_places=15, max_digits=15)),
                ('debito', models.DecimalField(decimal_places=15, max_digits=15)),
            ],
            options={
                'db_table': 'tipo_de_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('nombre_tour', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=11, max_digits=11)),
                ('fecha_tour', models.DateField()),
                ('hora_tour', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.DecimalField(decimal_places=11, max_digits=11, primary_key=True, serialize=False)),
                ('nombre_transporte', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('cod_postal', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
    ]
