# Generated by Django 4.1.1 on 2022-10-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estadia',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
