# Generated by Django 4.1.1 on 2022-11-05 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_costumer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.CharField(max_length=50)),
                ('condicion', models.CharField(max_length=50)),
                ('checkout', models.DateField()),
                ('checkin', models.DateField()),
                ('departamento_id_depto', models.ForeignKey(db_column='departamento_id_depto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.departamento')),
            ],
        ),
    ]
