# Generated by Django 4.1.1 on 2022-11-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ordendecompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_ws', models.CharField(default='0', max_length=255)),
                ('tarjeta', models.CharField(default='0', max_length=10)),
                ('fecha_transbank', models.CharField(default='0', max_length=100)),
                ('estado_transbank', models.CharField(default='0', max_length=100)),
                ('valor', models.PositiveBigIntegerField(default='0')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costumer')),
                ('departamento_id_depto', models.ForeignKey(db_column='departamento_id_depto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.departamento')),
                ('estado', models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estado')),
            ],
        ),
    ]
