# Generated by Django 4.1.2 on 2022-11-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ordendecompra1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExtra1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('valor', models.BigIntegerField()),
                ('reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
            ],
        ),
    ]
